### ISSUE TITLE
Nothing happens?

### ISSUE THREAD

**Issue by Askastaa** [FPtje/FProfiler#18] opened 2023-02-06 01:54 UTC
I gave myself admin in cami but the console command FProfiler dosent work ???
how dfq do i open the menu ? there is no real clear instruction how to install this

**Comment by FPtje** [comment] 2023-02-06 06:02
The install instructions are "free in addons folder", running instructions are indeed running FProfiler in console.

It should work, maybe the folder is not in addons correctly.

**Comment by Askastaa** [comment] 2023-02-06 09:45
and what about this superadmin stuff needed?

**Comment by Askastaa** [comment] 2023-02-06 10:05
update:
i changed myself to superadmin, still dosent work. I put this into my addon folder and it also loads. Whats going on here ?

**Comment by FPtje** [comment] 2023-02-06 11:15
I'm afraid I'm not going to look at your server to see what's wrong. Given that it worked for me when I tested it for the last issue, I would say this is something on your side.

Closing,because I'm not able to help further.

**Closed by FPtje** 2023-02-06 11:15 UTC

**Comment by Askastaa** [comment] 2023-02-06 11:36
you are able to helper fruther, its more you dont want to

**Comment by FPtje** [comment] 2023-02-06 12:03
The only debugging info I have "command doesn't work". I cannot work with that even if I wanted to. The only thing I could possibly do is have a look at your specific server. That goes beyond my responsibility as maintainer of this software.

FProfiler is a tool for developers, so I think I can ask you to print some debug statements to see what happens when you run the FProfiler command. Please do and see if you can find the problem that way. If it turns out to be a specific bug in FProfiler, I'd be glad to reproduce and fix it.

**Comment by Askastaa** [comment] 2023-02-06 13:20
already fixed the problem, i dont know what your dumbass did wrong but i turned this into a plugin system in my framework to force run it once, i was currently able to test client realm but not server realm because your dumbass uses a unnessecary complicated cami system.

also modifed the fprofiler file and changed the file paths which fixed my problem cause you just a dumbass

**Comment by Askastaa** [comment] 2023-02-06 13:21
> The only debugging info I have "command doesn't work". I cannot work with that even if I wanted to. The only thing I could possibly do is have a look at your specific server. That goes beyond my responsibility as maintainer of this software.
> 
> FProfiler is a tool for developers, so I think I can ask you to print some debug statements to see what happens when you run the FProfiler command. Please do and see if you can find the problem that way. If it turns out to be a specific bug in FProfiler, I'd be glad to reproduce and fix it.

you could ask for more detail as this is your code, you know it the best but apparently support isnt your main key

**Comment by FPtje** [comment] 2023-02-06 14:16
Thank you for confirming it was indeed a problem on your side.
