### ISSUE TITLE
attempt to call a userdata value

### ISSUE THREAD

**Issue by yunusemregul** [FPtje/FProfiler#10] opened 2019-03-12 22:39 UTC
when I try to start profiling on clientside and press the stop button, the following error occurs:

```
[ERROR] addons/fprofiler/lua/fprofiler/ui/frame.lua:245: attempt to call a userdata value
  1. func - addons/fprofiler/lua/fprofiler/ui/frame.lua:245
   2. updFunc - addons/fprofiler/lua/fprofiler/ui/model.lua:155
    3. update - addons/fprofiler/lua/fprofiler/ui/model.lua:76
     4. stopProfiling - addons/fprofiler/lua/fprofiler/ui/clientcontrol.lua:30
      5. updFunc - addons/fprofiler/lua/fprofiler/ui/clientcontrol.lua:43
       6. updateModel - addons/fprofiler/lua/fprofiler/ui/model.lua:76
        7. updateCurrentRealm - addons/fprofiler/lua/fprofiler/ui/model.lua:88
         8. DoClick - addons/fprofiler/lua/fprofiler/ui/frame.lua:179
          9. unknown - lua/vgui/dlabel.lua:234
```

**Comment by FPtje** [comment] 2019-03-14 19:32
Were you, by any chance on the X64 branch while this error happened?

**Comment by yunusemregul** [comment] 2019-03-14 19:36
> Were you, by any chance on the X64 branch while this error happened?

I absolutely was on x64 branch, didnt know that FProfiler is not compatible with it.

**Comment by Bo98** [comment] 2019-03-14 19:43
It was more the case of a GMod issue. The `continue` keyword was broken until 3 hours after you reported this error, which might have been the cause. Falco's testing it out now.

**Comment by FPtje** [comment] 2019-03-14 19:43
It isn't specifically, just untested. There was a bug in GMod where the `continue` keyword stopped working. Besides FProfiler that should break a ton of other stuff.

It should be fixed in the latest version of the X64 branch. Can you check?

**Comment by FPtje** [comment] 2019-03-14 19:46
I can't reproduce it in the latest X64 branch. Since `continue` was probably the cause, I'm going to close the issue. If it still occurs, it'll be re-opened.

**Closed by FPtje** 2019-03-14 19:46 UTC
